export const routePath = {
    HOME: "/",
    SEARCH: "search-page",
    ENTER_PAGE: "enter-page",
    NAME_PAGE: "name-page",
    RULES: "rules",
    AUTH: "auth",
    LOGIN: "login",
    CREATE_TEST: "create-test",
    CHANGE_PASSWORD: "change-password",
    SUCCESS_PAGE: "success",
    PAGE_NOT_FOUND: "*",
    SEARCH_PAGE: "search-page/:value",
    DETAIL: "detail/:name",
    RESTORE_PASSWORD: "restore-password",
    RESTORE_COMPLETE: "restore-complete",
};